routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/welcome', 'WelcomeController@index')->name('login');

//Auth::routes();
//
//Route::get('/home', 'HomeController@index')->name('home');

//Crawler
Route::get('/crawler/events', 'Crawlers\EventController@index');

//Pages
Route::get('/concepts/{slug}', 'ConceptController@show');
Route::get('/events/{slug}/lineup', 'EventController@lineup');
Route::get('/events/{slug}', 'EventController@show');

app/Models/Event.php
<?php namespace App\Models;

//use App\Models\File;
use Dimsav\Translatable\Translatable;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Model as Eloquent;
use Cerbero\QueryFilters\FiltersRecords;

class Event extends Eloquent
{
    use Translatable;
    use SoftDeletes;
    use FiltersRecords;

    public $translatedAttributes = [
        'name',
        'slug',
        'description'
    ];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'slug',
        'description',
        'fb_id'
    ];

    /**
     * The relations to eager load on every query.
     *
     * @var array
     */
    protected $with = [
        'translations'
    ];

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at'
    ];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $filters = [
        'name' => 'like',
//        'dates.starts_at' => '',
//        'dates.ends_at'
    ];

    /**
     * Get all of venue for the event.
     */
    public function venue()
    {
        return $this->belongsTo('App\Models\Venue');
    }

    /**
     * Get all of files for the event.
     */
    public function dates()
    {
        return $this->hasMany('App\Models\Date')->orderBy('starts_at');
    }

    /**
     * Get all of files for the event.
     */
    public function files()
    {
        return $this->morphToMany(File::class, 'filable')->withPivot('type', 'order');
    }

    /**
     * Get all of files for the event.
     */
    public function folder()
    {
        return $this->belongsTo('App\Models\Folder');
    }

    /**
     * Get all of the genres for the event.
     */
    public function genres()
    {
        return $this->morphToMany(Genre::class, 'genrable');
    }

//    /**
//     * Get all of files for the event.
//     */
//    public function images()
//    {
//        dd($this->files);
//    }

//    public function getActiveFilesAttribute()
//    {
//        $files = [];
//        $files['logo'] = $this->activeLogo;
//        $files['spotlight'] = $this->activeSpotlight;
//
//        return $files;
//    }

    public function getLogoAttribute()
    {
        return $this->files()->where('filables.type', 'logo')->orderBy('pivot_order', 'ASC')->first();
    }

    public function getSpotlightAttribute()
    {
        return $this->files()->where('filables.type', 'spotlight')->orderBy('pivot_order', 'ASC')->first();
    }

    /**
     * Get the URL of this event.
     */
    public function getPathAttribute()
    {
        return '/events/' . $this->slug;
    }

    /**
     * Get the URL of this event.
     */
    public function getLineupPathAttribute()
    {
        return $this->path . '/lineup';
    }

}

app/Http/Controllers/API/EventController.php
<?php namespace App\Http\Controllers\Api;

use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Models\Event;
use App\Models\Date;
use App\Http\Controllers\Controller;
use Spatie\Fractal\FractalFacade as Fractal;
use App\Transformers\EventTransformer;
use League\Fractal\Pagination\IlluminatePaginatorAdapter;
use App\QueryFilters\EventFilters;


class EventController extends Controller
{
    private $include;

    public function __construct(Request $request)
    {
//        $this->include = explode(',', Input::get('include'));

        $accept_language = strtolower($request->headers->get('accept-language'));
        if ($accept_language) {
            app()->setLocale($accept_language);
        }
    }

    public function index(Request $request)
    {
        $filters    = $request->input('filter');
        $cursor     = $request->get('cursor');
        $limit      = $request->get('limit');
        $fields     = $request->get('fields');

        $paginator = Event::select('events.*');

        if (!empty($filters)) {
            $filters = EventFilters::hydrate($request->input('filter', []));
            $paginator->filterBy($filters);
        }

        $paginator->join('dates', 'events.id', '=', 'dates.event_id')
            ->orderBy('dates.starts_at', 'ASC');

//        //TODO: whereHas?
//        if (!empty($filters['genres']) && str_contains($filters['genres'], ',')) {
//            $genres = explode(',', $filters['genres']);
//            foreach ($genres AS $column => $genre) {
//                $paginator->genres()->orWhere('name', $genre);
//            }
//        } elseif (!empty($filters['genres']) && !str_contains($filters['genres'], ',')) {
//            $paginator->genres()->whereTranslation('name', $filters['genres']);
//        }

//        dd($filters);

//        unset($filters['starts_at']);
//        unset($filters['ends_at']);
//        unset($filters['genres']);
//
//        if (!empty($filters) && is_array($filters)) {
//            foreach ($filters AS $column => $value) {
//                if (!empty($column) && !empty($value)) {
//                    $paginator = $paginator->whereTranslationLike($column, '%' . $value . '%');
//                }
//            }
//        }

//        dd($paginator->toSql());

        $paginator = $paginator->skip($cursor)->paginate($limit);

        $events = $paginator->getCollection();

//        foreach ($events as $event) {
//            dump($event->dates);
//        }

//        dd($events);
        $responds = Fractal::create()
            ->collection($events, new EventTransformer())
            ->serializeWith(new \League\Fractal\Serializer\JsonApiSerializer())
            ->withResourceName('events')
            ->paginateWith(new IlluminatePaginatorAdapter($paginator));

        if (!empty($fields)) {
            $responds->parseFieldsets($fields);
        }

        return $responds->respond();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @return Response
     */
    public function store(Request $request)
    {
        $event = new Event;

        $event->name = $request->name;
        $event->description = $request->description;

        $event->save();

        if (!empty($request->dates)) {
            foreach ($request->dates AS $key => $date) {
                $event_date[$key] = new Date;

                $event_date[$key]->name = $date['name'];
                $event_date[$key]->starts_at = $date['starts_at'];
                $event_date[$key]->ends_at = $date['ends_at'];
                $event_date[$key]->event_id = $event->id;

                $event_date[$key]->save();
            }
        }

//        if (!empty($request->venue)) {
//
//        }

        return Fractal::create()
            ->item($event, new EventTransformer())
            ->serializeWith(new \League\Fractal\Serializer\JsonApiSerializer())
//            ->parseIncludes($this->include)
            ->withResourceName('events')
            ->respond();
    }

    public function show(Event $event)
    {
        dd($event);
        if (empty($event) || !$event->exists) {
            return response()->json([
                'title' => 'Event not found',
                'status' => 404,
            ], 404);
        }
        return $this->transformer->item($event, new EventTransformer(), 'event');
    }

}

app/Http/Controllers/Crawlers/EventController.php
<?php namespace App\Http\Controllers\Crawlers;

use App\Models\Organizer;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Models\Event;
use App\Models\Date;
use App\Models\Venue;
use App\Models\Location;
use App\Models\City;
use App\Models\Country;
use App\Http\Controllers\Controller;
use Spatie\Fractal\FractalFacade as Fractal;
use App\Transformers\EventTransformer;
use League\Fractal\Pagination\IlluminatePaginatorAdapter;
use \Cviebrock\EloquentSluggable\Services\SlugService;
use GuzzleHttp\Exception\GuzzleException;
use GuzzleHttp\Client;

class EventController extends Controller
{
    private $include;
    private $soldOutTerms = [
        ' (SOLD OUT)',
        ' (Sold out)',
        ' - SOLD OUT',
        ' [SOLD OUT]',
        'SOLD OUT - ',
        'Sold out - ',
        ' [Sold Out]',
        ' - sold out -',
        ' (SOLD-OUT)',
        ' - Sold out'
    ];

    public function __construct(Request $request)
    {
//        $this->include = explode(',', Input::get('include'));

//        $accept_language = strtolower($request->headers->get('accept-language'));
//        if ($accept_language) {
//            app()->setLocale($accept_language);
//        }
    }

    public function index(Request $request)
    {
        $organizers = Organizer::whereNotNull('fb_event_page')->where('syncable', 1)->get();
        $organizers = $organizers->pluck('fb_event_page');
//        dd($organizers);

        $client = new Client(); //GuzzleHttp\Client

        foreach ($organizers as $key => $organizer) {
            $response = $client->get('https://graph.facebook.com/v2.12/' . $organizer . '/events?access_token=EAACEdEose0cBALfrcZBYfYWMkcNyASmqAB8leDV511NX0n5dBb2QCGYQxMhSNuP6waNWRRGp9cgCZAy56CjuCNF7nRUn93PFiK11QItMSGLDLlMpRponRhNy3uCZCL0SJMYGPxXBkAtl9456FhGO8z9mEoVuQpU3saLuHGF4i6hAy5nTlxPNkYG0ZATcNhHjWTxkwOTBrwZDZD&debug=all&format=json&method=get&pretty=0&suppress_http_code=1');
            $array = json_decode($response->getBody()->getContents(), true);

//        dd($array);

            foreach ($array['data'] as $event) {
                $this->saveEvent($event);
    //            dd($event);
            }
        }

        dd($array);
    }

    public function saveEvent($data)
    {
//        dd($data);
        $eventName = str_replace($this->soldOutTerms, '', $data['name']);

        $event = Event::whereTranslation('name', $eventName)->first();

        if (empty($event)) {
            $event = new Event;

            $event->name = $eventName;
            $event->description = !empty($data['description']) ? $data['description'] : '';
            $event->fb_id = $data['id'];

            $event->save();

            //Dates
            $event_date = new Date;
            $event_date->starts_at = !empty($data['start_time']) ? Carbon::createFromFormat('Y-m-d\TH:i:sP', $data['start_time']) : null;
            $event_date->ends_at = !empty($data['end_time']) ? Carbon::createFromFormat('Y-m-d\TH:i:sP', $data['end_time']) : null;
            //        $event_date->ends_at = $data['end_time'];
            $event_date->event_id = $event->id;

            $event_date->save();

            //Venue
            if (!empty($data['place'])) {
                $event_venue = Venue::whereTranslation('name', $data['place']['name'])->first();

                if (empty($event_venue)) {
                    $event_venue = new Venue;
                    $event_venue->name = !empty($data['place']['name']) ? $data['place']['name'] : null;
                    $event_venue->fb_id = !empty($data['place']['id']) ? $data['place']['id'] : null;

                    //            $event_venue->event_id = $event->id;

                    //Location
                    if (!empty($data['place']['location'])) {
                        $event_location = Location::where('latitude', $data['place']['location']['latitude'])
                            ->where('longitude', $data['place']['location']['longitude'])
                            ->first();

                        if (empty($event_location)) {
                            if (!empty($data['place']['location']['country'])) {
                                $country = Country::where('name', 'LIKE', $data['place']['location']['country'])->first();
                            } else {
                                $country = null;
                            }

                            $event_location = new Location;
                            $event_location->street_name = !empty($data['place']['location']['street']) ? $data['place']['location']['street'] : null;
                            $event_location->postal_area = !empty($data['place']['location']['zip']) ? $data['place']['location']['zip'] : null;
                            $event_location->latitude = !empty($data['place']['location']['latitude']) ? $data['place']['location']['latitude'] : null;
                            $event_location->longitude = !empty($data['place']['location']['longitude']) ? $data['place']['location']['longitude'] : null;
                            $event_location->country_id = !empty($country) ? $country->id : null;

                            if (!empty($data['place']['location']['city'])) {
                                $event_city = $this->findOrSaveCity($data['place']['location']['city'], $country);

                                $event_location->city_id = !empty($event_city) ? $event_city->id : null;
                            }

                            $event_location->save();
                        }

                        $event_venue->location_id = $event_location->id;
                    }

                    $event_venue->save();
                }

                $event->venue_id = $event_venue->id;
            }

            $event->save();
        }
    }

    public function findOrSaveCity($city, $country = null)
    {
        $event_city = City::whereTranslation('name', $city)->first();

        if (empty($event_city)) {
            $event_city = new City;
            $event_city->name = !empty($city) ? $city : null;
            $event_city->country_id = !empty($country) ? $country->id : null;

            $event_city->save();
        }

        return $event_city;
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @return Response
     */
    public function store(Request $request)
    {
//        $event = new Event;
//
//        $event->name = $request->name;
//        $event->description = $request->description;
//
//        $event->save();
//
//        if (!empty($request->dates)) {
//            foreach ($request->dates AS $key => $date) {
//                $event_date[$key] = new Date;
//
//                $event_date[$key]->name = $date['name'];
//                $event_date[$key]->starts_at = $date['starts_at'];
//                $event_date[$key]->ends_at = $date['ends_at'];
//                $event_date[$key]->event_id = $event->id;
//
//                $event_date[$key]->save();
//            }
//        }
//
////        if (!empty($request->venue)) {
////
////        }
//
//        return Fractal::create()
//            ->item($event, new EventTransformer())
//            ->serializeWith(new \League\Fractal\Serializer\JsonApiSerializer())
////            ->parseIncludes($this->include)
//            ->withResourceName('events')
//            ->respond();
    }

    public function show(Event $event)
    {
//        dd($event);
//        if (empty($event) || !$event->exists) {
//            return response()->json([
//                'title' => 'Event not found',
//                'status' => 404,
//            ], 404);
//        }
//        return $this->transformer->item($event, new EventTransformer(), 'event');
    }

}

app/Http/Controllers/EventController.php
<?php namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Event;

class EventController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
//        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }

    public function show($slug = null)
    {
        $event = Event::whereTranslation('slug', $slug)->first();
//        $spotlight = $event->files->where('pivot.type', 'spotlight')->first();
//        $logo = $event->files->where('pivot.type', 'logo')->first();
//        $active_files = $event->activeFiles;

        return view('events.details', ['event' => $event, 'spotlight' => $event->spotlight, 'logo' => $event->logo]);
    }

    public function lineup($slug = null)
    {
        $event = Event::whereTranslation('slug', $slug)->first();
        $spotlight = $event->files->where('pivot.type', 'spotlight')->first();
        $logo = $event->files->where('pivot.type', 'logo')->first();
//        dd($event);

        return view('events.performances', ['event' => $event, 'spotlight' => $spotlight, 'logo' => $logo]);
    }
}

resources/views/Events/details.blade.php
@extends('events.layout')

@section('page_content')
<div class="col-lg-3 rightbar">
    <div class="box">
        <h4>{{ trans('events.about') }}</h4>
        <ul class="list-group">
            <li class="list-group-item">
                <h6 class="list-item-title">{{ trans('events.genre') }}</h6>
                <div class="list-item-content">Techno</div>
            </li>
            <li class="list-group-item">
                <h6 class="list-item-title">{{ trans('events.first edition') }}</h6>
                <div class="list-item-content">1997</div>
            </li>
            <li class="list-group-item">
                <h6 class="list-item-title">
                    {{--@if (count($event->dates) >= 2)--}}
                        {{--{{ trans('events.dates') }}--}}
                    {{--@else--}}
                        {{--{{ trans('events.date') }}--}}
                    {{--@endif--}}
                </h6>
                <div class="list-item-content">
                    {{--@forelse($event->dates as $date)--}}
                        {{--<p>{{ $date->start_at->formatLocalized('%A %d %B %Y') }}</p>--}}
                    {{--@empty--}}
                        {{--<p>T.B.A.</p>--}}
                    {{--@endforelse--}}
                </div>
            </li>
            <li class="list-group-item">
                <h6 class="list-item-title">Cras justo odio</h6>
                <div class="list-item-content">Dapibus ac facilisis in</div>
            </li>
            <li class="list-group-item">
                <h6 class="list-item-title">Cras justo odio</h6>
                <div class="list-item-content">Dapibus ac facilisis in</div>
            </li>
        </ul>
    </div>
</div>

<div class="col-lg-6">
    <div class="box">
        <h4>{{ trans('events.description') }}</h4>
        {!! $event->description !!}
        <small>Bron: Wikipedia</small>
    </div>
</div>

<div class="col-lg-3">
    <div class="box">
        <h4>{{ trans('events.about') }}</h4>
    </div>
</div>
@endsection

resources/views/Events/layout.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
    <div class="container spotlight">
        <div class="row">
            <div class="col-lg-12">
                <div class="spotlight-background" style="background-image: url('{{ $spotlight->path }}');">
                    <div class="spotlight-info">
                        <div class="spotlight-logo">
                            <img class="img-fluid" src="{{ $logo->path }}" title="{{ $event->name }}" alt="{{ $event->name }}" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container name">
    <div class="row">
        <div class="col-lg-12">
            <h1>{{ $event->name }}</h1>
        </div>
    </div>
</div>

<div class="container navbar-entity navbar-events">
        <div class="navbar navbar-expand-lg">
            <nav class="collapse navbar-collapse justify-content-md-center">
                <ul class="nav navbar-nav">
                    <li class="nav-item active">
                        <a href="{!! $event->path !!}" class="btn">
                            Latest <!--<span class="badge badge-secondary">9</span>-->
                            <span class="sr-only">unread messages</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{!! $event->lineup_path !!}" class="btn">
                            Lineup <!--<span class="badge badge-secondary">9</span>-->
                            <span class="sr-only">unread messages</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="btn">
                            Photos <!--<span class="badge badge-secondary">9</span>-->
                            <span class="sr-only">unread messages</span>
                        </a>
                    </li>
                </ul>
            </nav>
        </div>
</div>

<div class="container-fluid">
    <div class="container main">
        <div class="row">
            @yield('page_content')
        </div>
    </div>
</div>
@endsection

resources/views/Events/performances.blade.php
@extends('events.layout')

@section('page_content')
<div class="col-lg-3 rightbar">
    <div class="box">
        <h4>About</h4>
        <ul class="list-group">
            <li class="list-group-item">
                <div class="list-item-title">First edition</div>
                <div class="list-item-content">1997</div>
            </li>
            <li class="list-group-item">
                <div class="list-item-title">Cras justo odio</div>
                <div class="list-item-content">Dapibus ac facilisis in</div>
            </li>
            <li class="list-group-item">
                <div class="list-item-title">Cras justo odio</div>
                <div class="list-item-content">Dapibus ac facilisis in</div>
            </li>
            <li class="list-group-item">
                <div class="list-item-title">Cras justo odio</div>
                <div class="list-item-content">Dapibus ac facilisis in</div>
            </li>
        </ul>
    </div>
</div>

<div class="col-lg-6">
    <div class="box">
        <h4>Description</h4>
        llineup
        {!! $event->description !!}
        <small>Bron: Wikipedia</small>
    </div>
</div>

<div class="col-lg-3">
    <div class="box">
        <h4>About</h4>
    </div>
</div>
@endsection