routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/welcome', 'WelcomeController@index')->name('login');

//Auth::routes();
//
//Route::get('/home', 'HomeController@index')->name('home');

//Crawler
Route::get('/crawler/events', 'Crawlers\EventController@index');

//Pages
Route::get('/concepts/{slug}', 'ConceptController@show');
Route::get('/events/{slug}/lineup', 'EventController@lineup');
Route::get('/events/{slug}', 'EventController@show');

app/Models/Folder.php
<?php namespace App\Models;

use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Model as Eloquent;

class Folder extends Eloquent
{
    use SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
    ];

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = [
        'created_at', 'updated_at', 'deleted_at'
    ];

    /**
     * Get all of files for in the folder.
     */
    public function files()
    {
        return $this->hasMany('App\Models\file');
    }

    public function getPathAttribute($value)
    {
        return 'images/'.$value;
    }
}

app/Http/Controllers/ConceptController.php
<?php namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Event;

class ConceptController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
//        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }

    public function show($slug = null)
    {
        $event = Event::whereTranslation('slug', $slug)->first();
        $spotlight = $event->files->where('pivot.type', 'spotlight')->first();
        $logo = $event->files->where('pivot.type', 'logo')->first();
//        dd($event);

        return view('events.layout', ['event' => $event, 'spotlight' => $spotlight, 'logo' => $logo]);

//        dd($slug);

//        $id = PageSettings::get('product_id');
//        $lang = locale();
//
//        if(empty($id)) {
//            $product = Product::where('id', '=', $slug)->first();
//        }
//        else {
//            $product = Product::where('id', '=', $id)->first();
//        }
//
//        if (empty($product)) {
//            abort(404);
//        }
//
//        return view('product' . (empty($id) ? 's' : '') . '.show.' . PageSettings::getDisplayView(locale(), 'show'), compact('product', 'lang'));
    }
}

resources/views/concept/layout.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <div class="row spotlight">
            <div class="container">
                <div class="col-lg-12">
                    <div class="spotlight-background" style="background-image: url('/{{ $logo->path }}{{ $logo->original_name }}');">
                        <div class="spotlight-info">
                            <div class="spotlight-logo">
                                <img src="/{{ $spotlight->path }}{{ $spotlight->original_name }}" title="Awakenings logo" alt="Awakenings logo" />
                            </div>
                            <h1>{{ $event->name }}</h1>
                            <h2>Techno</h2>
                            <div class="row spotlight-count">
                                <div class="col-lg-6 spotlight-count-box">
                                    <div class="spotlight-count-number">
                                        10.000.000
                                    </div>
                                    <div class="spotlight-count-name">
                                        Likes
                                    </div>
                                </div>
                                <div class="col-lg-6 spotlight-count-box">
                                    <div class="spotlight-count-number">
                                        10.000.000
                                    </div>
                                    <div class="spotlight-count-name">
                                        Followers
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

        <nav class="navbar navbar-entity navbar-events">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="#" class="active">Latest</a>
                </li>
                <li>
                    <a href="#">Photos</a>
                </li>
                <li>
                    <a href="#">Events</a>
                </li>
            </ul>
        </nav>

    <div class="container-fluid">
        <div class="row main">
            <div class="container">
                <div class="col-lg-3 rightbar">
                    <div class="card">
                        <h4>About</h4>
                        <ul class="list-group">
                            <li class="list-group-item">
                                <div class="list-item-title">First edition</div>
                                <div class="list-item-content">1997</div>
                            </li>
                            <li class="list-group-item">
                                <div class="list-item-title">Cras justo odio</div>
                                <div class="list-item-content">Dapibus ac facilisis in</div>
                            </li>
                            <li class="list-group-item">
                                <div class="list-item-title">Cras justo odio</div>
                                <div class="list-item-content">Dapibus ac facilisis in</div>
                            </li>
                            <li class="list-group-item">
                                <div class="list-item-title">Cras justo odio</div>
                                <div class="list-item-content">Dapibus ac facilisis in</div>
                            </li>
                        </ul>
                    </div>
                </div>

                <div class="col-lg-6">
                    <div class="card">
                        <h4>Description</h4>
                        {!! $event->description !!}
                        <small>Bron: Wikipedia</small>
                    </div>
                </div>

                <div class="col-lg-3">
                    <div class="card">
                        <h4>About</h4>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection